//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "command_runs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub command: String,
    pub args: Json,
    pub working_dir: Option<String>,
    pub log_path: Option<String>,
    pub title: Option<String>,
    pub env: Option<Json>,
    pub status: String,
    pub exit_code: Option<i32>,
    pub started_at: DateTime,
    pub completed_at: Option<DateTime>,
    pub server_id: Option<i64>,
    pub log_removed: bool,
    pub pid: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
