//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "game_servers")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub app_id: i32,
    pub name: String,
    pub install_dir: String,
    pub platform: String,
    pub status: String,
    pub pid: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub boot_script: Option<String>,
    pub auto_start: bool,
    pub auto_restart: bool,
    pub auto_update: bool,
    pub update_on_start: bool,
    pub restart_schedule: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub server_mod: Option<String>,
    pub beta_branch: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
