//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "game_templates")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub app_id: i32,
    pub server_mod: Option<String>,
    pub beta_branch: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub boot_script: Option<String>,
    pub use_steam_login: bool,
    pub auto_start: bool,
    pub auto_restart: bool,
    pub auto_update: bool,
    pub update_on_start: bool,
    pub restart_schedule: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::game_servers::Entity")]
    GameServers,
}

impl Related<super::game_servers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameServers.def()
    }
}
